services:
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
      - "10000-10100:10000-10100"
      - "10000-10100:10000-10100/udp"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydb
      - DEBUG=mediasoup:*
      # - ANNOUNCED_IP=host.docker.internal
    volumes:
      - ./packages/backend:/app
      - /app/node_modules
    # depends_on:
    #   - db

  # db:
  #   image: postgres:14
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: mydb
  #   volumes:
  #     - db_data:/var/lib/postgresql/data

volumes:
  db_data:
